import './globals.css'
import { Josefin_Sans } from 'next/font/google'

const josefinsans = Josefin_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'TODO  App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon-32x32.png" type='image/png' sizes="any" />
      </head>
      <body className={josefinsans.className}>{children}</body>
    </html>
  )
}
