
import './globals.css'
import { Roboto } from 'next/font/google'
import { EmailProvider } from '@/components/EmailProvider'

const roboto = Roboto({ 
  subsets: ['latin'],
  weight: ["400", "500", "700", "900"]
})

export const metadata = {
  title: 'Frontend Mentor | Newsletter sign-up form with success message',
  description: 'Generated by create next app',
  icons: {
    icon: {
      url: "/favicon-32x32.png",
      sizes: "32x32",
      type: "image/png"
    }
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
        <body className={roboto.className}><EmailProvider>{children}</EmailProvider></body>
      
    </html>
  )
}
