import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Frontend Mentor | Newsletter sign-up form with success message',
  description: 'Generated by create next app',
  icons: {
    icon: {
      url: "./assets/images/favicon-32x32.png",
      sizes: "32x32",
      type: "image/png"
    }
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
